# week 1

### 변수의 자료형

### 숫자 int, float

숫자 자료형에는 정수를 나타내는 int, 소수까지 나타내는 float이 존재

In [3]:
a = 1; print(type(a))

<class 'int'>


In [4]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [5]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


### 문자열 str

index로 문자열에 접근할 수 있으며 맨 첫 index는 0

In [6]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


### 리스트 list
문자열을 리스트로 변환할 수 있고, 리스트 안의 리스트도 존재할 수 있다. 

In [7]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [8]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


### 튜플 tuple

리스트와 비슷하지만 괄호 모양이 다름

In [9]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


### 딕셔너리 dictionary

중괄호 안에 짝을 지어서 존재, key를 통해 해당하는 value를 찾을 수 있다. 

In [10]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


### tuples in list

In [11]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

### numpy

위의 a라는 튜플로 이루어진 리스트를 np.array로 변환, 타입은 numpy.ndarray

In [12]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


### b 안의 각 요소가 곱하기 연산

In [13]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


###  numpy array b를 matrix로 변환

In [14]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrix'>


c는 2x3 matrix 이므로 c와 c를 행렬 연산 하는 것은 앞 행렬의 열과 뒷 행렬의 행의 사이즈가 맞지 않아 불가능하다. 

In [15]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

대신 c.T 를 이용하면 행렬 c가 transpose 되어 3x2 matrix로 변하게 되어 행렬 연산이 가능해진다. 

In [17]:
c*c.T

matrix([[14, 19],
        [19, 73]])